import React, { useState } from 'react';
import { ArrowLeft, ArrowUpRight, FileCheck2, Sprout, MapPin, Wallet, CalendarDays, ShieldCheck, ChevronRight, Check, Download } from 'lucide-react';
import Logo from './Logo';
import { money, number, download } from '../api';

export default function FarmerServicesPage({ context, ask, navigate }: { context: Record<string, any> | null; ask: (q?: string) => void; navigate: (hash: string) => void }) {
  const [checked, setChecked] = useState<string[]>([]);
  const docs = ['Identity proof', 'Land ownership records', 'Recent bank statements', 'Crop and income details'];
  const amount = context?.sanctioned_amount_inr ?? context?.max_sanction_amount_inr;
  return <div className="farmer-page"><header className="farmer-top"><a href="#home" className="farmer-logo"><Logo /><strong>GeoKisaan</strong><span>Farmer services</span></a><button onClick={() => navigate('home')}><ArrowLeft size={16} />Back to website</button></header>
    <main id="website-main" className="farmer-main"><div className="farmer-intro"><div><span className="section-kicker">YOUR FARM. YOUR AMBITIONS.</span><h1>{context?.applicant_name ? `Welcome, ${context.applicant_name.split(' ')[0]}.` : 'Your next season starts here.'}</h1><p>Your application, documents and guidance. All in one place.</p></div><button className="portal-primary" onClick={() => navigate(context ? 'underwriting' : 'signin')}>{context ? 'View assessment' : 'Sign in to your account'}<ArrowUpRight size={17} /></button></div>
    <div className="farmer-layout"><div className="farmer-main-column"><section className="farmer-account"><div className="farmer-account-top"><span><Sprout size={18} />AGRICULTURAL FINANCE</span><span>{context ? 'Assessment available' : 'Ready when you are'}</span></div><h2>{context ? 'A clearer picture of your application.' : 'Finance that understands your farm.'}</h2><p>{context ? 'Review the latest assessment details and prepare for the next step.' : 'Start with your farm details. Understand your options, then plan the way forward.'}</p><div className="farmer-account-stats"><div><span>Proposed amount</span><strong>{money(amount)}</strong></div><div><span>Assessment score</span><strong>{number(context?.agri_credit_score)}</strong></div><div><span>District</span><strong>{context?.district || 'Not selected'}</strong></div></div><div className="farmer-account-bottom"><span>{context ? 'Assessment result · not a disbursed loan' : 'No application is linked yet'}</span><button onClick={() => navigate('underwriting')}>{context ? 'Review details' : 'Start an assessment'}<ChevronRight size={17} /></button></div></section>
    <section className="farmer-checklist"><div className="portal-section-title"><div><span className="section-kicker">BEFORE YOU APPLY</span><h2>A little preparation goes a long way.</h2></div><span>{checked.length} / {docs.length} ready</span></div><p>Use this checklist to prepare. Documents have not been uploaded or verified.</p><div className="document-list">{docs.map((doc, i) => <label key={doc}><span className="doc-number">0{i + 1}</span><span><strong>{doc}</strong><small>{['A valid government-issued identity document','Khasra or other relevant parcel records','Statements showing your banking activity','Crop type, cultivated area and seasonal income'][i]}</small></span><input type="checkbox" checked={checked.includes(doc)} onChange={e => setChecked(prev => e.target.checked ? [...prev, doc] : prev.filter(x => x !== doc))} /><span className="doc-check"><Check size={16} /></span></label>)}</div><button className="portal-text" onClick={() => download('farm-document-checklist.txt', docs.map(doc => `${checked.includes(doc) ? '[Ready]' : '[To prepare]'} ${doc}`).join('\n'), 'text/plain')}><Download size={16} />Save my checklist</button></section>
    <section className="farmer-journey"><div className="portal-section-title"><h2>Your path to a decision</h2></div><div>{[{icon: FileCheck2, title:'Prepare', text:'Keep your farm and financial details ready.'},{icon: ShieldCheck,title:'Assess',text:'Request a review of your application.'},{icon: CalendarDays,title:'Plan',text:'Discuss terms and repayment dates with your officer.'}].map((step,i) => <article key={step.title}><step.icon size={22}/><small>0{i+1}</small><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section></div>
    <aside className="farmer-side"><section className="farmer-saathi"><img src="/saathi-icon.png" alt="" /><span className="section-kicker">MEET YOUR FARM COMPANION</span><h2>A question today.<br />Clarity for tomorrow.</h2><p>Talk about documents, crop health or harvest repayments in your language.</p><button onClick={() => ask()}>Ask Krishi Saathi<ArrowUpRight size={17}/></button><small>Available in 8 languages</small></section><section className="farmer-support"><h3>How can we help?</h3>{[{icon:Wallet,text:'Understand repayments',q:'How do harvest repayments work?'},{icon:MapPin,text:'Prepare land records',q:'Which land records should I prepare for a farm loan?'},{icon:Sprout,text:'Understand crop health',q:'How is crop health used in an agricultural credit assessment?'}].map(item=><button key={item.text} onClick={()=>ask(item.q)}><item.icon size={18}/>{item.text}<ChevronRight size={16}/></button>)}</section></aside></div>
    <footer className="farmer-footer"><span>GeoKisaan · Smart Lending Hub</span><span>Built by Team BioXtreme</span></footer></main></div>;
}
