import React, { useState } from 'react';
import { ArrowLeft, ArrowUpRight, ArrowRight, Sprout, MessageCircle, FileText, CalendarDays, ShieldCheck, ChevronDown } from 'lucide-react';
import '../portals.css';
interface Props { onBackToCockpit: () => void; onOpenSignIn?: () => void }
const ask = (query = '') => window.dispatchEvent(new CustomEvent('open-krishi-saathi', { detail: { query } }));
const documents = ['Identity & address proof', 'Land record / Khasra details', 'Recent bank statements', 'Crop & income information'];
export default function FarmerWorkspace({ onBackToCockpit, onOpenSignIn }: Props) {
  const [checked, setChecked] = useState<string[]>([]);
  const [user] = useState(() => { try { return JSON.parse(localStorage.getItem('tvs_credit_user') || 'null'); } catch { return null; } });
  const scroll = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' });
  return <div className="portal-ui farmer-shell"><header className="farmer-header"><button className="portal-brand" onClick={onBackToCockpit}><span className="portal-mark"><Sprout size={23}/></span><span>TVS CREDIT<small>FARMER SERVICES</small></span></button><nav aria-label="Farmer navigation"><button onClick={() => scroll('farmer-assistant')}>Your Saathi</button><button onClick={() => scroll('farmer-journey')}>Your next steps</button><button onClick={() => scroll('farmer-documents')}>Documents</button></nav><button className="portal-btn secondary" onClick={user ? onBackToCockpit : onOpenSignIn}>{user ? 'Back to website' : 'Sign in'}<ArrowUpRight size={16}/></button></header>
    <main className="farmer-content"><div className="farmer-greeting"><div><span className="portal-eyebrow">YOUR FARM. YOUR FUTURE.</span><h1>{user?.name ? `Welcome, ${user.name.split(' ')[0]}.` : 'A little clarity. A big step forward.'}</h1><p>Your loan journey, documents and questions. All in one place.</p></div><span className="farmer-service-badge"><Sprout size={17}/>Farmer services</span></div>
    <section className="farmer-voice-feature" id="farmer-assistant"><div className="saathi-copy"><span className="saathi-pill"><span className="status-dot"/>MEET YOUR KRISHI SAATHI</span><h2>Big questions?<br/>Let’s talk it through.</h2><p>Understand farm loans, prepare your documents, or make sense of repayments — in a language you’re comfortable with.</p><div className="portal-actions"><button className="portal-btn light" onClick={() => ask()}><MessageCircle size={20}/>Talk to Saathi <ArrowUpRight size={18}/></button><span className="saathi-mode">Type or record a question<br/>Choose your language in chat</span></div></div><div className="saathi-visual"><div className="saathi-halo"><img src="/saathi-icon.png" alt="Krishi Saathi"/></div><div className="saathi-sample"><span>TRY ASKING</span><button onClick={() => ask('What documents should I prepare for a farm loan?')}>“What do I need for a farm loan?” <ArrowUpRight size={16}/></button></div></div><div className="saathi-quick">{['Explain harvest-based repayments in simple terms.', 'How can crop health affect a credit assessment?', 'Help me prepare for a loan application.'].map((query, i) => <button key={query} onClick={() => ask(query)}>{['Understand repayments', 'Explore crop health', 'Prepare an application'][i]}<ArrowRight size={16}/></button>)}</div></section>
    <div className="farmer-section-heading" id="farmer-journey"><div><span className="portal-eyebrow">ONE STEP AT A TIME</span><h2>Make your next move with confidence.</h2></div><span>Simple steps. Useful information.</span></div>
    <div className="farmer-service-grid"><article className="farmer-service lavender"><span className="service-icon"><FileText size={23}/></span><span className="service-number">01</span><h3>Your application</h3><p>Start with your details and understand what a lending officer will need.</p><span className="service-status">{user ? 'Account signed in' : 'Get started'}</span><button className="portal-link" onClick={user ? () => ask('What are the next steps to prepare my agricultural loan application?') : onOpenSignIn}>{user ? 'Plan my next steps' : 'Sign in to begin'}<ArrowRight size={17}/></button></article><article className="farmer-service mint"><span className="service-icon"><CalendarDays size={23}/></span><span className="service-number">02</span><h3>Your repayments</h3><p>Learn how a repayment schedule can align with your harvest and income.</p><span className="service-status">No repayment account linked</span><button className="portal-link" onClick={() => ask('Explain how harvest-based repayments work, and what I should check before agreeing to a loan.')}>Understand my options <ArrowRight size={17}/></button></article><article className="farmer-service sand"><span className="service-icon"><Sprout size={23}/></span><span className="service-number">03</span><h3>Your farm insights</h3><p>Find out how land records, rainfall and crop health inform an assessment.</p><span className="service-status">Farm report not linked</span><button className="portal-link" onClick={() => ask('Explain the land, rainfall and crop health information used in an agricultural credit assessment.')}>Explore farm insights <ArrowRight size={17}/></button></article></div>
    <div className="farmer-details-grid"><section className="portal-card farmer-documents" id="farmer-documents"><div className="portal-card-heading"><div><span className="portal-eyebrow">BE READY BEFORE YOU APPLY</span><h2>Your document checklist</h2><p>A personal preparation list. Requirements depend on your product.</p></div><span className="checklist-count">{checked.length}/{documents.length}</span></div><div className="checklist-progress" role="progressbar" aria-label="Document preparation" aria-valuemin={0} aria-valuemax={documents.length} aria-valuenow={checked.length}><i style={{ width: `${checked.length / documents.length * 100}%` }}/></div>{documents.map((doc, i) => <label className="farmer-check" key={doc}><input type="checkbox" checked={checked.includes(doc)} onChange={e => setChecked(prev => e.target.checked ? [...prev, doc] : prev.filter(d => d !== doc))}/><span><b>{doc}</b><small>{['Keep valid identification ready.', 'Have your plot reference and ownership details.', 'Gather statements showing your banking activity.', 'Note your primary crop and seasonal income.'][i]}</small></span><FileText size={19}/></label>)}<div className="checklist-note"><ShieldCheck size={16}/>Ticking an item marks it ready here; it does not upload or verify a document.</div></section>
    <section className="farmer-help"><span className="portal-eyebrow">GOOD TO KNOW</span><h2>Clear answers.<br/>Less back and forth.</h2>{[['Where can I see my loan balance?', 'A verified loan account must be connected before a balance or due date can be shown. Ask your lending officer for your current statement.'], ['Can I speak instead of typing?', 'Yes. Open Saathi, choose your language, and use the microphone to record a question. You can review the words before sending.'], ['Does an assessment approve my loan?', 'An assessment helps an officer review the application. Your lender confirms approval, final terms and the repayment schedule.']].map(([q, a]) => <details key={q}><summary>{q}<ChevronDown size={17}/></summary><p>{a}</p></details>)}<button className="portal-btn secondary" onClick={() => ask('I need help understanding the next step in my loan journey.')}><MessageCircle size={17}/>Ask a different question</button></section></div>
    <footer className="portal-footer"><button className="portal-link" onClick={onBackToCockpit}><ArrowLeft size={15}/>Back to website</button><span>BioXtreme · Built for rural progress</span></footer></main></div>;
}
